PE_or_SE: PE

ref: /primary/projects/bbc/references/human/sequence/hg38/gdna/primary_assembly/ucsc/hg38_ucsc_pa.fa

idx: /primary/projects/bbc/references/human/indexes/hg38/bwa/hg38_ucsc_pa.fa

report: 2020-05-21_PFEG-20200427-CDseq.4HNE
